### PR TITLE
Multithreaded Demo Viewer

### PR DESCRIPTION
**Pull request by monster860**
New and improved multithreaded demo viewer! Featuring:

- better performance
- improved UI
- touchscreen support
- probably some other things I forgot

things I still need to do
- [x] replay streaming
- [x] fix context menu on iOS safari
- [x] make context menu based on visual location and not actual location

image

image

### CODE REVIEW

**Comment by ToasterBiome** [comment]
OOOOOOOOoooooooooo

**Comment by Hislyna** [comment]
Are you not able to see all chats at once without following a ghost?

**Comment by ToasterBiome** [comment]
Text is a little large on PC

**Comment by Hopekz** [comment]
> Are you not able to see all chats at once without following a ghost?

I like the whole "only see what that person saw" part of it

**Comment by Hislyna** [comment]
ive found another issue, on PC you cannot easily scroll down the clients to find who you need

**Pull request merged**
