### PR TITLE
Fix unstable overlay sort behavior across browsers

### PR DESCRIPTION
**Pull request by Chubbygummibear**
Chromium's javascript engine lets you get away with a comparison function that only returns <0 and 0 values, however firefox does not. changing the sort to a method that uses all 3, albeit less effectively, should streamline the behavior

also updates values to match plane cube pr

### CODE REVIEW

**Review by ToasterBiome — APPROVED** [review]

**Review by monster860 — CHANGES_REQUESTED** [review]
this is way more complicated than it needs to be lol I'm pretty sure you can just do `if(the one thing != the other thing)` rather than <

**Comment by Chubbygummibear** [comment]
> this is way more complicated than it needs to be lol I'm pretty sure you can just do `if(the one thing != the other thing)` rather than <

i'll try that. the reason i made this so many steps was so that the sorting behavior could be controlled for each plane of overlays. it was very cool how condensed you had it to begin with like with the for loop of a shallow copy that gets sorted, but when you do so many things at the same time it made it extremely difficult to untangle what was happening until i could fix it. so i'm hesitant to try and re-condense if someone tries to make edits later on and just comes back to the same bundle of code that confused me for a week

**Comment by Chubbygummibear** [comment]
after more deliberation and explaining what was going on with the sorting logic to a few other people, i don't think the code should be re-consolidated. i think readability and maintainability is more important in this case than compressing the code into as few operations as possible, even if that would yield slightly more performance improvements or optimization

**Comment by monster860** [comment]
Unfortunately the code you wrote doesn't work correctly and puts all the non-float layers on top of the float layers no matter what which is not correct behavior.

**Comment by Chubbygummibear** [comment]
> Unfortunately the code you wrote doesn't work correctly and puts all the non-float layers on top of the float layers no matter what which is not correct behavior.

can you elaborate on this? i came up with my solution by matching the exact output of your sorting method when it worked on chromium browsers. i kept tweaking mine until its output matched what you had

**Comment by monster860** [comment]
The code you put will put *any* layer that's not FLOAT_LAYER below FLOAT_LAYER no matter what which is incorrect behavior.

**Comment by Chubbygummibear** [comment]
> The code you put will put _any_ layer that's not FLOAT_LAYER below FLOAT_LAYER no matter what which is incorrect behavior.

can you indicate what needs to be changed or give me an example i should check from a game replay where i can observe the correct output vs mine?

**Comment by monster860** [comment]
I'd need to go and look in order to find an example of incorrect behavior but I can tell you that it will produce incorrect behavior. Also sorting multiple times is just icky to me.

**Comment by Chubbygummibear** [comment]
> I'd need to go and look in order to find an example of incorrect behavior but I can tell you that it will produce incorrect behavior. Also sorting multiple times is just icky to me.

i'm going to assume this is the behavior you're referring to about the negative layers taking precedence over everything else
image

however this is already a feature of the live version
image
image

this can be remedied after the baseline functionality is reached for all browsers rather than trying to fix a logic issue while also trying to bring everyone up to speed. as for the multiple sorts, sure it's less efficient and maybe even redundant, but it significantly improves readability and maintainability so others will have less difficulty approaching this code to make changes in the future

**Review by monster860 — CHANGES_REQUESTED** [review]
If you're *abso-fucking-lutely* dead-set on using multiple sorts then you need three arrays and three sorts to get the correct result. One for regular layers less than the parent layer, one for FLOAT_LAYER layers, and one for regular layers bigger than the parent layer.

**Comment by Chubbygummibear** [comment]
ok so after a lot of testing yesterday it seems like every overlay is getting sorted appropriately due to your overlay proxy object and sorting method in player. the reason screens are showing up over paper is because the sprites are getting re-rendered on the EMISSIVE_PLANE which in byond is just an alpha mask for the darkness layer. i'd need to figure out how to do better plane mixing than just blending to make it work as it should. the Emissives, Above Lighting, and Emissive Blockers should all just be various alpha filters for lighting. this is why i was asking about the array of textures as plane masters in discord 😩

**Comment by Chubbygummibear** [comment]
ok i literally think the solution here is to implement multiple webGL texture channels and have one dedicated to game world sprites and another dedicated to light mixing before merging them together. This is because planes 12, 13, and 14 should be added to plane 15, and plane 16 should be an alpha mask of 15. then plane 15 should be multiplied to the game's appearance. however i believe this to be such a change that it should be its own PR, and i'm going to request that this be merged as is because it matches previous behavior, while aligning the sorting outcome on all browsers

**Comment by Chubbygummibear** [comment]
updated all the plane values to match the new plane cube update pr that some idiot made

**Pull request merged**
